package com.example.ui.auth;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;
import androidx.activity.result.ActivityResult;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.AppCompatButton;
import com.example.R;
import com.example.data.FirebaseManager;
import com.example.ui.MainActivity;
import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.ApiException;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthCredential;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.GoogleAuthProvider;

/**
 * Real authentication screen backed by Firebase Auth (email/password + Google).
 * There is no local/fake account creation here anymore - every sign in / sign up
 * call actually talks to Firebase, and failures are surfaced to the user.
 */
public class AuthActivity extends AppCompatActivity {

    private boolean isSignUp = false;
    private EditText etUsername, etEmail, etPassword;
    private AppCompatButton btnSubmitAuth, btnGoogleSignIn;
    private TextView tvToggleAuthMode, tvAuthHeader, tvAuthSubtitle;
    private ProgressBar pbAuthLoading;

    private FirebaseAuth firebaseAuth;
    private GoogleSignInClient googleSignInClient;

    private final ActivityResultLauncher<Intent> googleSignInLauncher = registerForActivityResult(
            new ActivityResultContracts.StartActivityForResult(),
            this::onGoogleSignInResult
    );

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_auth);

        firebaseAuth = FirebaseAuth.getInstance();

        etUsername = findViewById(R.id.etUsername);
        etEmail = findViewById(R.id.etEmail);
        etPassword = findViewById(R.id.etPassword);
        btnSubmitAuth = findViewById(R.id.btnSubmitAuth);
        btnGoogleSignIn = findViewById(R.id.btnGoogleSignIn);
        tvToggleAuthMode = findViewById(R.id.tvToggleAuthMode);
        tvAuthHeader = findViewById(R.id.tvAuthHeader);
        tvAuthSubtitle = findViewById(R.id.tvAuthSubtitle);
        pbAuthLoading = findViewById(R.id.pbAuthLoading);

        setupGoogleSignIn();

        tvToggleAuthMode.setOnClickListener(v -> toggleAuthMode());
        btnSubmitAuth.setOnClickListener(v -> handleAuthSubmit());
        btnGoogleSignIn.setOnClickListener(v -> handleGoogleSignIn());
    }

    private void setupGoogleSignIn() {
        // default_web_client_id is generated by the google-services Gradle plugin from
        // google-services.json ONLY if Google Sign-In is enabled for the Firebase project.
        // We look it up at runtime so the app still builds/runs if it's not configured yet.
        int webClientIdRes = getResources().getIdentifier("default_web_client_id", "string", getPackageName());
        if (webClientIdRes == 0) {
            btnGoogleSignIn.setEnabled(false);
            btnGoogleSignIn.setAlpha(0.4f);
            btnGoogleSignIn.setText("Google Sign-In not configured");
            return;
        }
        String webClientId = getString(webClientIdRes);
        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(webClientId)
                .requestEmail()
                .build();
        googleSignInClient = GoogleSignIn.getClient(this, gso);
    }

    private void toggleAuthMode() {
        isSignUp = !isSignUp;
        if (isSignUp) {
            tvAuthHeader.setText("Create M.SHAREX Account");
            tvAuthSubtitle.setText("Experience original quality photo & video transfer");
            etUsername.setVisibility(View.VISIBLE);
            btnSubmitAuth.setText("Create Account");
            tvToggleAuthMode.setText("Already have an account? Sign In");
        } else {
            tvAuthHeader.setText("Welcome to SHAREX");
            tvAuthSubtitle.setText("Sign in to share original 4K & RAW media");
            etUsername.setVisibility(View.GONE);
            btnSubmitAuth.setText("Sign In");
            tvToggleAuthMode.setText("Don't have an account? Sign Up");
        }
    }

    private void setLoading(boolean loading) {
        pbAuthLoading.setVisibility(loading ? View.VISIBLE : View.GONE);
        btnSubmitAuth.setEnabled(!loading);
        btnGoogleSignIn.setEnabled(!loading && googleSignInClient != null);
    }

    private void handleAuthSubmit() {
        String email = etEmail.getText().toString().trim();
        String password = etPassword.getText().toString().trim();
        String username = etUsername.getText().toString().trim();

        if (email.isEmpty() || password.isEmpty()) {
            Toast.makeText(this, "Please fill in all required fields", Toast.LENGTH_SHORT).show();
            return;
        }
        if (password.length() < 6) {
            Toast.makeText(this, "Password must be at least 6 characters", Toast.LENGTH_SHORT).show();
            return;
        }
        if (isSignUp && username.isEmpty()) {
            Toast.makeText(this, "Please enter a unique username", Toast.LENGTH_SHORT).show();
            return;
        }

        setLoading(true);
        if (isSignUp) {
            firebaseAuth.createUserWithEmailAndPassword(email, password)
                    .addOnSuccessListener(result -> onFirebaseAuthSuccess(username))
                    .addOnFailureListener(this::onFirebaseAuthFailure);
        } else {
            firebaseAuth.signInWithEmailAndPassword(email, password)
                    .addOnSuccessListener(result -> onFirebaseAuthSuccess(null))
                    .addOnFailureListener(this::onFirebaseAuthFailure);
        }
    }

    private void onFirebaseAuthSuccess(String username) {
        FirebaseManager.getInstance(this).ensureUserProfile(firebaseAuth.getCurrentUser(), username, user -> {
            setLoading(false);
            Toast.makeText(this, "Welcome to M.SHAREX!", Toast.LENGTH_SHORT).show();
            goToMain();
        });
    }

    private void onFirebaseAuthFailure(Exception e) {
        setLoading(false);
        String message = e.getMessage() != null ? e.getMessage() : "Authentication failed. Please try again.";
        Toast.makeText(this, message, Toast.LENGTH_LONG).show();
    }

    private void handleGoogleSignIn() {
        if (googleSignInClient == null) {
            Toast.makeText(this, "Google Sign-In requires a Firebase project with Google Sign-In enabled.", Toast.LENGTH_LONG).show();
            return;
        }
        setLoading(true);
        googleSignInLauncher.launch(googleSignInClient.getSignInIntent());
    }

    private void onGoogleSignInResult(ActivityResult result) {
        Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(result.getData());
        try {
            GoogleSignInAccount account = task.getResult(ApiException.class);
            AuthCredential credential = GoogleAuthProvider.getCredential(account.getIdToken(), null);
            firebaseAuth.signInWithCredential(credential)
                    .addOnSuccessListener(authResult -> onFirebaseAuthSuccess(account.getDisplayName()))
                    .addOnFailureListener(this::onFirebaseAuthFailure);
        } catch (ApiException e) {
            setLoading(false);
            Toast.makeText(this, "Google Sign-In failed: " + e.getStatusCode(), Toast.LENGTH_LONG).show();
        }
    }

    private void goToMain() {
        startActivity(new Intent(AuthActivity.this, MainActivity.class));
        finish();
    }
}
